<a href="https://colab.research.google.com/github/usamasansi/AiRespository/blob/main/02_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch


In [2]:
# input (temp, rainfall, humidity)
inputs = np.array([[73, 67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [3]:

# Targets (apples, oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 1.0726,  0.7610,  0.1324],
        [ 0.7208, -1.5128,  1.1389]], requires_grad=True)
tensor([ 1.2830, -0.2921], requires_grad=True)


In [6]:
w.t()

tensor([[ 1.0726,  0.7208],
        [ 0.7610, -1.5128],
        [ 0.1324,  1.1389]], grad_fn=<TBackward0>)

In [7]:
b.t()

tensor([ 1.2830, -0.2921], grad_fn=<TBackward0>)

In [8]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [9]:
inputs @ w.t() + b

tensor([[ 1.3627e+02, -5.9982e-02],
        [ 1.7434e+02,  5.0617e+00],
        [ 2.0426e+02, -7.4246e+01],
        [ 1.4832e+02,  5.0320e+01],
        [ 1.5762e+02, -1.6066e+01]], grad_fn=<AddBackward0>)

In [10]:
def model(x):
    return x @ w.t() + b

In [11]:
preds = model(inputs)
print(preds)


tensor([[ 1.3627e+02, -5.9982e-02],
        [ 1.7434e+02,  5.0617e+00],
        [ 2.0426e+02, -7.4246e+01],
        [ 1.4832e+02,  5.0320e+01],
        [ 1.5762e+02, -1.6066e+01]], grad_fn=<AddBackward0>)


In [12]:
#compare with target
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [13]:
preds - targets

tensor([[  80.2676,  -70.0600],
        [  93.3375,  -95.9383],
        [  85.2581, -207.2459],
        [ 126.3155,   13.3196],
        [  54.6221, -135.0664]], grad_fn=<SubBackward0>)

In [14]:
diff = preds - targets
torch.sum(diff * diff) / diff.numel()

tensor(11684.6709, grad_fn=<DivBackward0>)

In [15]:
# mse loss
def mse(t1,t2):
  diff = t1 - t2
  return torch.sum(diff * diff) /diff.numel()

In [16]:
# compute loss
loss = mse(preds, targets)
print(loss)
# sqrt 249.87

tensor(11684.6709, grad_fn=<DivBackward0>)


In [17]:
# compute gradeinet  such as autograd in pytorch
loss.backward()

In [18]:
# gradients for weight
print(w)
print(w.grad)


tensor([[ 1.0726,  0.7610,  0.1324],
        [ 0.7208, -1.5128,  1.1389]], requires_grad=True)
tensor([[  7684.7627,   7138.3018,   4573.4604],
        [ -7967.2305, -10660.2373,  -6026.9448]])


In [19]:
print(inputs)
print(inputs.grad)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
None


In [20]:
print(b)
print(b.grad)

tensor([ 1.2830, -0.2921], requires_grad=True)
tensor([ 87.9602, -98.9982])


In [21]:
w.grad

tensor([[  7684.7627,   7138.3018,   4573.4604],
        [ -7967.2305, -10660.2373,  -6026.9448]])

In [22]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [23]:
#adjust weight and biases using gradient descent
# grrnral prediction
preds = model(inputs)
print(preds)
# calculate the loss
loss = mse(preds, targets)
print(loss)

tensor([[ 1.3627e+02, -5.9982e-02],
        [ 1.7434e+02,  5.0617e+00],
        [ 2.0426e+02, -7.4246e+01],
        [ 1.4832e+02,  5.0320e+01],
        [ 1.5762e+02, -1.6066e+01]], grad_fn=<AddBackward0>)
tensor(11684.6709, grad_fn=<DivBackward0>)


In [24]:
# calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(11684.6709, grad_fn=<DivBackward0>)


In [25]:
# compute losss
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  7684.7627,   7138.3018,   4573.4604],
        [ -7967.2305, -10660.2373,  -6026.9448]])
tensor([ 87.9602, -98.9982])


In [26]:
w

tensor([[ 1.0726,  0.7610,  0.1324],
        [ 0.7208, -1.5128,  1.1389]], requires_grad=True)

In [27]:
w.grad * 1e-5

tensor([[ 0.0768,  0.0714,  0.0457],
        [-0.0797, -0.1066, -0.0603]])

In [28]:
# Adjust weight and  reset gradeint
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [29]:
print(w)
print(b)

tensor([[ 0.9958,  0.6896,  0.0867],
        [ 0.8005, -1.4062,  1.1991]], requires_grad=True)
tensor([ 1.2821, -0.2911], requires_grad=True)


In [30]:
# again calculate loss
preds = model(inputs)
loss =- mse(preds, targets)
print(loss)

tensor(-8546.9053, grad_fn=<NegBackward0>)


In [31]:
# train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [32]:
# calculate loss agin
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(627.2233, grad_fn=<DivBackward0>)


In [33]:
# prediction?
preds

tensor([[ 63.0021,  79.0277],
        [ 81.0781, 112.9693],
        [111.8804,  90.9691],
        [ 53.2557,  88.6186],
        [ 81.4326, 110.3630]], grad_fn=<AddBackward0>)

In [34]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

**used linear regression and gradient descent with basic tensor operation above**

*now we are going to implement pytorch linear regression*

In [35]:
import torch.nn as nn

In [36]:
# inputs (temp, rainfall, humidity)
inputs =  np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102,43,37],
                    [69,96,70],
                    [74,55,43],
                    [91,87,65],
                    [88,134,59],
                    [101,44,37],
                    [68,96,71],
                    [73,66,44],
                    [92,87,64],
                    [87,135,57],
                    [103,43,36],
                    [68,97,70]],dtype='float32')

In [37]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119,133],
                    [22, 37],
                    [103, 119],
                    [57,69],
                    [80,102],
                    [118,132],
                    [21, 38],
                    [104,118],
                    [57,69],
                    [82,100],
                    [118,134],
                    [20,38],
                    [102,120]],dtype='float32')
inputs =torch.from_numpy(inputs)
targets =torch.from_numpy(targets)

In [38]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  55.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [39]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [40]:
from torch.utils.data import TensorDataset

In [41]:
train_ds  = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [42]:
from torch.utils.data import DataLoader

In [43]:
# define dataloader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [44]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  55.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [45]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 69.,  96.,  70.],
        [ 68.,  97.,  70.],
        [ 73.,  67.,  43.],
        [ 87., 135.,  57.],
        [ 74.,  55.,  43.]])
tensor([[103., 119.],
        [102., 120.],
        [ 56.,  70.],
        [118., 134.],
        [ 57.,  69.]])


In [46]:
# define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4614, -0.0882,  0.1393],
        [-0.3080, -0.1971,  0.5699]], requires_grad=True)
Parameter containing:
tensor([-0.3469,  0.1785], requires_grad=True)


In [47]:
#p[ara,meters
list(model.parameters())

[Parameter containing:
 tensor([[-0.4614, -0.0882,  0.1393],
         [-0.3080, -0.1971,  0.5699]], requires_grad=True),
 Parameter containing:
 tensor([-0.3469,  0.1785], requires_grad=True)]

In [48]:
# generate prediction
preds = model(inputs)
preds

tensor([[-3.3948e+01, -1.1001e+01],
        [-4.1180e+01, -8.7142e+00],
        [-4.4226e+01, -1.9966e+01],
        [-4.6048e+01, -1.8623e+01],
        [-3.0899e+01, -9.5280e-02],
        [-3.3351e+01, -8.9440e+00],
        [-4.0952e+01, -7.9472e+00],
        [-4.4548e+01, -1.9704e+01],
        [-4.5674e+01, -1.8512e+01],
        [-3.0298e+01,  7.8264e-01],
        [-3.3720e+01, -1.0234e+01],
        [-4.1553e+01, -8.8251e+00],
        [-4.4454e+01, -2.0733e+01],
        [-4.6648e+01, -1.9501e+01],
        [-3.0525e+01,  1.5659e-02]], grad_fn=<AddmmBackward0>)

In [49]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [50]:
# import nn.functional
import torch.nn.functional as F

In [51]:
# Define loss functiomn
loss_fn = F.mse_loss

In [52]:
loss = loss_fn(model(inputs), targets)
print (loss)

tensor(13098.6562, grad_fn=<MseLossBackward0>)


In [53]:
# define optimi\zer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [54]:
# utility function to train the mpodel
def fit(num_epochs, model, loss_fn, opt, train_dl):
  # rapeat for given number of epechs
  for epoch in range(num_epochs):
    # train with batches of data?
    for xb, yb in train_dl:
      # geneerate prediction #1
      pred = model(xb)

      # calulate loss
      loss = loss_fn(pred, yb)
      # compute gradinencs?
      loss.backward()
      #  update parameters using gradients
      opt.step()
      #reset gradient to zero
      opt.zero_grad()

      # print the progress
  if (epoch + 1) % 10 == 0:
   print('Epoch [{}/{}], loss: {:.4f}'.format(epoch+1, num_epochs,loss.item()))


In [55]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [100/100], loss: 13.7441


In [56]:
preds = model(inputs)
preds

tensor([[ 58.0365,  71.4660],
        [ 82.2561, 101.9067],
        [117.6664, 129.6966],
        [ 26.0383,  42.4902],
        [ 99.0105, 118.0276],
        [ 47.8865,  62.7660],
        [ 82.0268, 102.1329],
        [117.9559, 130.4080],
        [ 27.1608,  43.4182],
        [ 99.9038, 119.1819],
        [ 57.8072,  71.6922],
        [ 81.1336, 100.9787],
        [117.8957, 129.4703],
        [ 25.1451,  41.3360],
        [100.1331, 118.9556]], grad_fn=<AddmmBackward0>)

In [57]:
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [58]:
# suppose data for temp, rainfall , humidity
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.7414, 69.1297]], grad_fn=<AddmmBackward0>)